 {!! Form::select('cstate', 
	[	'0'=>'Select State',
		'Andaman and Nicobar Islands' => 'Andaman and Nicobar Islands',
		'Andhra Pradesh'=>'Andhra Pradesh',
		'Arunachal Pradesh'=>'Arunachal Pradesh',
		'Assam'=>'Assam',
		'Bihar'=>'Bihar',
		'Chandigarh'=>'Chandigarh',
		'Chhattisgarh'=>'Chhattisgarh',
		'Dadra and Nagar Haveli'=>'Dadra and Nagar Haveli',
		'Daman and Diu'=>'Daman and Diu',
		'Delhi'=>'Delhi',
		'Goa'=>'Goa',
		'Gujrat'=>'Gujrat',
		'Haryana'=>'Haryana',
		'Himachal Pradesh'=>'Himachal Pradesh',
		'Jammu and Kashmir'=>'Jammu and Kashmir',
		'Jharkhand'=>'Jharkhand',
		'Karnataka'=>'Karnataka',
		'Kerala'=>'Kerala',
		'Lakshadweep'=>'Lakshadweep',
		'Madhya Pradesh'=>'Madhya Pradesh',
		'Maharashtra'=>'Maharashtra',
		'Manipur'=>'Manipur',
		'Meghalaya'=>'Meghalaya',
		'Mizoram'=>'Mizoram',
		'Nagaland'=>'Nagaland',
		'Orissa'=>'Orissa',
		'Pondicherry'=>'Pondicherry',
		'Punjab'=>'Punjab',
		'Rajasthan'=>'Rajasthan',
		'Sikkim'=>'Sikkim',
		'Tamil Nadu'=>'Tamil Nadu',
		'Tripura'=>'Tripura',
		'Uttar Pradesh'=>'Uttar Pradesh',
		'Uttaranchal'=>'Uttaranchal',
		'West Bengal'=>'West Bengal'

	],                                 
	($per->cstate)?$per->cstate:"null", 
	['class' => 'form-control','id'=>'state','data-error'=>'Please select your state']) !!} 

